### ISSUE TITLE
Command bugs

### ISSUE THREAD

**Issue by kevinzying** [aneeshdurg/what_is_a_filesystem#27]
Hi, came across this in CS 4410.

- [ ] Typing 'help' results in no help information being output, and the command appear to hang and not produce another prompt or respond to additional commands.
- [ ] Typing 'stat' with a non-existent file or without giving a file argument results in the same behavior (with an error message if no filename is given).

**Comment by aneeshdurg** [comment]
Thanks for reporting this! If you're interested in contributing, fixing the bug with `stat` should be really easy!


Some notes from a really quick look into the problem:
+ Looking at the console while running `stat`, we see a crash due to `TypeError: path is undefined`

+ when running `help` there's a crash because `ReferenceError: possible_commands is not defined`.
